title: Not Hotdog training images
hero_image: images/banner.png
description: a collection of images of things which are not hotdogs for training a machine learning model
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Not Hotdog training images